# Generated by Django 5.1.5 on 2025-02-01 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Points', to='accounts.game'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shots', to='accounts.point'),
        ),
    ]
