# Generated by Django 5.1.5 on 2025-02-03 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_point_game_alter_shot_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='accounts.game'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='accounts.point'),
        ),
    ]
