# Generated by Django 5.1.5 on 2025-02-03 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_point_game_alter_shot_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='game',
            new_name='game_id',
        ),
        migrations.RenameField(
            model_name='shot',
            old_name='point',
            new_name='point_id',
        ),
    ]
