# Generated by Django 5.1.5 on 2025-02-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_game_point_game_id_rename_point_shot_point_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='shot',
            old_name='point_id',
            new_name='point',
        ),
    ]
